### PR TITLE
Add information about queue and priority

### LINKED ISSUE #341: Add queue information to task_enqueued log
Is there a way to add queue information to this log?
```
    logger.info( 
         "task_enqueued", 
         child_task_id=headers.get("id") if headers else body.get("id"), 
         child_task_name=headers.get("task") if headers else body.get("task"), 
     )
```

Something like
````
    logger.info( 
         "task_enqueued", 
         child_task_id=headers.get("id") if headers else body.get("id"), 
         child_task_name=headers.get("task") if headers else body.get("task"), 
         priority=,
         queue=
     )
````

### PR DESCRIPTION
**Pull request by jrobichaud**
Todo:
- [x] add `task_routing_key` and `task_properties` to `modify_context_before_task_publish`
- [x] refactor celery receivers and command receivers modules to use classes
- [x] (maybe?) log queue/routing_key and priority in `task_enqueued`
- [x] documentation

Closes #341

### CODE REVIEW

**Comment by jrobichaud** [comment]
@mohamedTbarka it is not finished but I will have to store data somewhere between "receiver_before_task_publish" and "receiver_after_task_publish"

the value of priority is available in the first but I want to use it in the second.

I did not want to store the value in a global variable.

**Comment by mohamedTbarka** [comment]
@jrobichaud, I think it's slickly done; I needed just a clarification :pray:

**Comment by jrobichaud** [comment]
@mohamedTbarka 

I discovered two things about signals:

1. the connected functions need to continue to exist or they get disconnected. (ex: if the function is declared and connected in a function, it will be disconnected when exiting the function). This is why i keep a reference of the instance in the app or the bootstep.
2. the receivers can actually be methods (I discovered that yesterday). 🤯

**Comment by mohamedTbarka** [comment]
@jrobichaud, thank u a lot for the clarifications :pray:. I think I need to play more with the signals to grasp why such behavior exists :thinking:

**Comment by jrobichaud** [comment]
Since it seems like people are watching me working on this, what is your opinion about logging or not `routing_key`?

**Comment by badziyoussef** [comment]
> Since it seems like people are watching me working on this, what is your opinion about logging or not `routing_key`?

I would say Yes, because sometimes, task is enqueued and queues are full, I would like to know the content of any desired queue and I can do that if I have `routing_key` part of the log `task_enqueued`

**Comment by jrobichaud** [comment]
@badziyoussef thanks for the concrete example. 

Anything else from [before_task_publish](https://docs.celeryq.dev/en/stable/userguide/signals.html#before-task-publish) or [after_task_publish](https://docs.celeryq.dev/en/stable/userguide/signals.html#after-task-publish) would be useful to be added to the `task_enqueued` event?

**Pull request merged**
