### PR TITLE
Use structlog.contextvars

### PR DESCRIPTION
**Pull request by jrobichaud**
This is the continuity of Andrew Guenter's work.

Todo:
- [ ] complete documentation
- [x] Fix CI
- [x] fix pypi metadata
- [x] fix standard loggers no longer using bound values

### CODE REVIEW

**Comment by jrobichaud** [comment]
@AndrewGuenther replacing `inject_context_dict` with `structlog.contextvars.merge_contextvars`  causes the side effect of standard loggers to no longer add context. 

This is a regression, it works on master.

image

```
django-structlog-django-1        | 2022-04-01T02:23:22.163337Z [info     ] This is a standard logger      [foreign_logger]
```

master:
```
django-structlog-django-1        | 2022-04-01T02:27:26.289183Z [info     ] This is a standard logger      [foreign_logger] ip=172.18.0.1 request_id=5dc264aa-f4d0-45ef-b531-87d96165c3ed user_id=None
```

**Comment by AndrewGuenther** [comment]
Can you point me to where that demo project config is and where that log is emitted from?

**Comment by jrobichaud** [comment]
@AndrewGuenther

Make sure to rebase your branch on the branch of this repository. I merged your branch early thinking wrongly it was the reason the CI was not working but it was completely unrelated, I had to switch from Travis to github actions.

## The config:
`config/settings/local.py`

```
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
```

## The view:
`django-structlog/django_structlog_demo_project/home/views.py`
```
def log_with_standard_logger(request):
    logging.getLogger("foreign_logger").info("This is a standard logger")
    return HttpResponse(status=200)
```

**Comment by shimizukawa** [comment]
Now structlog-22.1.0 has been released the entire `structlog.threadlocal` module is deprecated. 
https://github.com/hynek/structlog/releases/tag/22.1.0

**Comment by jrobichaud** [comment]
@shimizukawa there is a regression when using standard no one took the time to look at. I might consider release the new version with the regression and document it.

**Comment by shimizukawa** [comment]
@jrobichaud I probably could have fixed it. Please check it out.
https://github.com/jrobichaud/django-structlog/pull/81

**Comment by merwok** [comment]
PR title has a typo in `structlog` name

**Comment by jrobichaud** [comment]
For those currently watching this issue, I am currently actively working on it. 

I have a few more things to validate before to release. 

It should be ready by tomorrow.

Thanks for your patience.

**Comment by jrobichaud** [comment]
`django-structlog` `3.0.0` is released on pypi. 

Upgrade guide:
https://django-structlog.readthedocs.io/en/latest/upgrade_guide.html#upgrading-to-3-0

Please create new issues or PR if you notice anything wrong.

**Comment by shimizukawa** [comment]
Thanks @jrobichaud, great job!

**Pull request merged**
