### PR TITLE
setup dependabot

### PR DESCRIPTION
**Pull request by jairhenrique**
Configure dependabot to keep ci dependencies up to date.

### CODE REVIEW

**Comment by jrobichaud** [comment]
I never used dependabot and never took the time to look at it. 

I hope you can enlighten me about a few things.

The context of `django-structlog`:)
- readthedocs use some older versions of packages [`requirements/docs.txt`](https://github.com/jrobichaud/django-structlog/blob/master/requirements/doc.txt) and I have to run (tests and build) of the doc using versions compatible with what readthedocs use
- some packages may use older versions for compatibility when testing older version with `tox` (https://github.com/jrobichaud/django-structlog/blob/master/tox.ini).
- there are multiple requirements files for different use-case but none of them are included in the released package. Running tests, the demo app, the docs, and when ran in the CI.

I maintained the versions of the packages manually because of this complexity.

I also just realized the new CI setup I did does not run on your merge request (I have to look at that).

I am not sure what its going to happen when I merge this PR.

**Comment by jrobichaud** [comment]
Thanks, Ill merge that tonight and complete the configuration after.

**Review by jrobichaud — APPROVED** [review]

**Comment by jrobichaud** [comment]
Issues I encountered:
- it does not validate if the peer dependencies are met. Ex: `celery` was updated but `kombu` was not.
- the demo project is currently not fully tested (ex: building the images and run some checkups)
-  its limited to 5 PR at time

I will have to manually test all dependency updates for the moment.

I will most likely have to strip down the demo project to avoid unnecessary dependency updates.

**Comment by jairhenrique** [comment]
@jrobichaud you can increase pr limitations with [this settings](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit)

**Comment by jrobichaud** [comment]
Thanks, good to know!

I will consider this if after I updated all dependencies its still a problem.

**Pull request merged**
